apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-book-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
        - name: my-book-app
          image: khuramshah/book-tracker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-svc
spec:
  selector:
    app: book-app
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: LoadBalancer
#apiVersion: v1
#kind: Service
#metadata:
#  name: angular-app-svc
#  namespace: default
#spec:
##  selector:
##    app: angular-app
##  ports:
##    - protocol: TCP
##      port: 8085
##      targetPort: 8085
##  type: LoadBalancer
#  type: ExternalName
#  externalName: my.poc.example.com