apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ak-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: my-angular-app
          image: khuramshah/book-tracker:26
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-svc
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
#apiVersion: v1
#kind: Service
#metadata:
#  name: angular-app-svc
#  namespace: default
#spec:
##  selector:
##    app: angular-app
##  ports:
##    - protocol: TCP
##      port: 8085
##      targetPort: 8085
##  type: LoadBalancer
#  type: ExternalName
#  externalName: my.poc.example.com