# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest

steps:
 - task: Maven@3
   inputs:
     mavenPomFile: 'pom.xml'
     goals: 'clean install'
     publishJUnitResults: true
     testResultsFiles: '**/surefire-reports/TEST-*.xml'
     javaHomeOption: 'JDKVersion'
     mavenVersionOption: 'Default'
     mavenAuthenticateFeed: false
     effectivePomSkip: false
     sonarQubeRunAnalysis: false
 - task: Docker@2
   displayName: build and Push image
   inputs:
     containerRegistry: 'khuramshah89 docker hub'
     repository: 'khuramshah/book-tracker'
     command: 'buildAndPush'
     Dockerfile: '**/Dockerfile'
     tags: |
       $(tag)
- task: CopyFiles@2
  # displayName:''
  inputs:
    Contents: '*.yaml'
    TargetFolder: $(build.artifactstagingdirectory)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop-build'
    publishLocation: 'Container'
# - task: Docker@2
#   displayName: login docker
#   inputs:
#     containerRegistry: 'my docker hub'
#     command: 'login'
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '44d207d5-7d79-4b2c-badc-a4913b3a88b2'
    pipeline: '1'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'specific'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure service connection poc'
    azureResourceGroup: 'poc'
    kubernetesCluster: 'pocAKSCluster'
    useClusterAdmin: true
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '/home/vsts/work/1/a/drop-build/aks-deploy-docker-hub.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
# - task: Kubernetes@1
#   inputs:
#     connectionType: 'Kubernetes Service Connection'
#     kubernetesServiceEndpoint: 'k8sServiceConnection poc'
#     namespace: 'default'
#     command: 'apply'
#     useConfigurationFile: true
#     configuration: '$(System.DefaultWorkingDirectory)/_khuram-shehzad-confiz.book-tracker/drop-build/aks-deploy-docker-hub.yaml'
#     secretType: 'dockerRegistry'
#     containerRegistryType: 'Azure Container Registry'
 